### ISSUE TITLE
Virus scanners flagging up EICAR test files

### ISSUE THREAD

**Issue by machisuji** [franckverrot/clamav-client#16]
We have included the clamav-client gem in OpenProject and someone [brought up](https://community.openproject.org/topics/18677?r=18677#message-18677) that their virus scanner is flagging up the EIRCAR test files in the clamav-client's fixtures. This is of course nothing to be worried about but still tedious if one has to deal with this.

Would it be possible to simply not include the tests in the published ruby gem, perhaps?
I'm not sure what the best practice here is.

**Comment by Jack12816** [comment]
Hey there,
the linked issue seems to fixed with a upstream update of the OpenProject project.

I checked version 3.2.0 of the clamav-client gem, and it does not ship the fixtures anymore [since 2016](https://github.com/franckverrot/clamav-client/commit/21cb291d4f884895230c14222f954033ea888a47). With the release 3.2.0, [pushed to RubyGems 2020](https://rubygems.org/gems/clamav-client/versions/3.2.0).

The posted path on the link is:

```
/opt/openproject/vendor/bundle/ruby/3.2.0/bundler/gems/clamav-client-29e78ae94307/test/fixtures/
```

which indicates a [git checkout](https://github.com/franckverrot/clamav-client/commit/29e78ae94307) to a fork commit from:
* https://rubygems.org/gems/op-clamav-client
* https://github.com/opf/clamav-client

This just seems to was an issue of the fork, not being in sync with this upstream repo. So this issue should be closed, right?

**Comment by franckverrot** [comment]
Agreed, closing now, thanks!
