### ISSUE TITLE
GPL license is limiting

### ISSUE THREAD

**Issue by adin-ttc** [franckverrot/clamav-client#8]
Not sure if this is something that could be altered. But GPL does limit my ability to make use of this gem. 

http://stackoverflow.com/questions/3902754/mit-vs-gpl-license

"if you DO distribute it, then your entire project that is using the GPL code also becomes GPL automatically. Which means, it must be open-sourced"

**Comment by franckverrot** [comment]
I've put some thoughts before choosing the GPL and know the "limitations" it brings with it.

To try to understand a bit better your situation, may I ask how you will "distribute" the gem?

I am asking because:
* If you're building a SaaS, as long as you/your company is hosting it, the GPL doesn't require you to open-source anything.
* If you distribute an app, bundled against this gem, to your clients so they can host it themselves, then yes, you will have to open-source it **unless** you contract a commercial license to the author (me, in that case).

If you'd like more info, don't hesitate to ask them here or shoot me an email (franck $$ verrot $$ fr).

Thanks!

**Comment by adin-ttc** [comment]
Thanks for the feedback and reassessing this. 

In the corp world most lawyers are very weary of the wording. You are mostly correct in your points, however, I still cant make use of anything GPL... Also according to our interpretation we would have to make our entire source code available even if not providing it as "open-source". 

I'm sure I will be able to figure out how to talk to clamAV

**Comment by franckverrot** [comment]
> Also according to our interpretation we would have to make our entire source code available even if not providing it as "open-source".

Depends on how you operate. A hosted SaaS product **can** use GPL in a way that doesn't make it GPL too.

@adin-ttc In any case, would your company be willing to acquire a commercial license (**not GPL-licensed**) of this gem?
